### ISSUE TITLE
compute.tbl_sql calls as.sql without passing in the con argument

### ISSUE THREAD

**Issue by ablack3** [tidyverse/dbplyr#1031]
I want to use `compute` to transform a dplyr query into a persistent table in a sql server database. I get the following error.

``` r
library(dplyr, warn.conflicts = F)
con <- DBI::dbConnect(odbc::odbc(),
                      Driver   = "ODBC Driver 18 for SQL Server",
                      Server   = Sys.getenv("CDM5_SQL_SERVER_SERVER"),
                      Database = Sys.getenv("CDM5_SQL_SERVER_CDM_DATABASE"),
                      UID      = Sys.getenv("CDM5_SQL_SERVER_USER"),
                      PWD      = Sys.getenv("CDM5_SQL_SERVER_PASSWORD"),
                      TrustServerCertificate = "yes",
                      Port     = 1433)

concept <- tbl(con, dbplyr::in_catalog("cdmv5", "dbo", "concept"))

db <- concept %>% 
  filter(concept_id == 0) %>% 
  select(starts_with("concept")) %>% 
  compute(name = DBI::Id(catalog = "tempdb", schema = "dbo", table = "temp_example9"), temporary = FALSE)
#> Error in h(simpleError(msg, call)): error in evaluating the argument 'conn' in selecting a method for function 'dbQuoteIdentifier': argument "con" is missing, with no default

DBI::dbDisconnect(con)
```

<sup>Created on 2022-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

When I step through the code the table is created as expected. The error is caused by a call to `as.sql(name)` without passing in the connection. The method being called is `as.sql.Id`.

**compute.tbl_sql**
```
function (x, name = unique_table_name(), temporary = TRUE, unique_indexes = list(), 
  indexes = list(), analyze = TRUE, ..., cte = FALSE) 
{
  name <- unname(name)
  vars <- op_vars(x)
  assert_that(all(unlist(indexes) %in% vars))
  assert_that(all(unlist(unique_indexes) %in% vars))
  x_aliased <- select(x, !!!syms(vars))
  sql <- db_sql_render(x$src$con, x_aliased$lazy_query, cte = cte)
  name <- db_compute(x$src$con, name, sql, temporary = temporary, 
    unique_indexes = unique_indexes, indexes = indexes, 
    analyze = analyze, ...)
  tbl_src_dbi(x$src, as.sql(name), colnames(x)) %>% group_by(!!!syms(op_grps(x))) %>% 
    window_order(!!!op_sort(x))
}
```

Changing 
`tbl_src_dbi(x$src, as.sql(name), colnames(x)) %>% group_by(!!!syms(op_grps(x))) %>% 
    window_order(!!!op_sort(x))`

to 
`tbl_src_dbi(x$src, as.sql(name, x$src$con), colnames(x)) %>% group_by(!!!syms(op_grps(x))) %>% 
    window_order(!!!op_sort(x))`

fixes the problem since `as.sql.Id` requires both the name and connection arguments.
https://github.com/tidyverse/dbplyr/blob/e4f909a4a019bafe48ed24bd80132aef9fbc81e9/R/schema.R#L82

If this is a suitable solution I can make the PR for this change.

**Comment by wangyuchen** [comment]
I encounter the same issue and also came to realize this came from the `as.sql(name)` call.  Despite that `compute()` throws an error, it actually doesn't prevent the writing of the table, because the `db_compute()` step creates the table eagerly, I think. 

Another thing that threw me off was the `name <- unname(name)` in `compute.tbl_sql`. The documentation said that name is "table name in remote database" but doesn't say what's acceptable and how to specify a schema. I finally found that using `DBI::Id` like you did works. But for a while I was trying to use `dbplyr::in_schema()`. It's a little strange that the in-package solution doesn't work here and you had to call another package for this.
