### ISSUE TITLE
Filtering with external vector and max gives `lazy_select_query` error

### ISSUE THREAD

**Issue by chwpearse** [tidyverse/dbplyr#1048]
Filtering a dbplyr table with col %in% ext_vector & col == max(col) causes an error. This works in version 2.1.1, but not 2.2.0

Either of these statements by themselves, or split into seperate filter functions run correctly.

``` r
library(tidyverse)
library(dbplyr)
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

lf <- lazy_frame(x = 1L)

to_filter <- c('a', 'b')

lf %>% filter(x == max(x, na.rm = T))
#> <SQL>
#> SELECT `x`
#> FROM (
#>   SELECT *, MAX(`x`) OVER () AS `q01`
#>   FROM `df`
#> ) `q01`
#> WHERE (`x` = `q01`)
lf %>% filter(x %in% to_filter)
#> <SQL>
#> SELECT *
#> FROM `df`
#> WHERE (`x` IN ('a', 'b'))
lf %>% filter(x == max(x, na.rm = T)) %>% filter(x %in% to_filter)
#> <SQL>
#> SELECT *
#> FROM (
#>   SELECT `x`
#>   FROM (
#>     SELECT *, MAX(`x`) OVER () AS `q01`
#>     FROM `df`
#>   ) `q01`
#>   WHERE (`x` = `q01`)
#> ) `q02`
#> WHERE (`x` IN ('a', 'b'))

lf %>% filter(x == max(x, na.rm = T), x %in% to_filter)
#> Error in lazy_select_query(x = mutated$lazy_query, last_op = "filter", : is_lazy_sql_part(where) is not TRUE
```

<sup>Created on 2022-11-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lf <- lazy_frame(x = 1L)
to_filter <- c('a', 'b')

lf %>% filter(x == max(x, na.rm = TRUE), x %in% to_filter)
#> Error in lazy_select_query(x = mutated$lazy_query, last_op = "filter", : is_lazy_sql_part(where) is not TRUE
```

<sup>Created on 2022-12-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

@mgirlich The problem is that `is_lazy_sql_part()` is returning false because the second query element (`x %in% to_filter`) is not an expression because by that point the value of `to_filter` has been inlined into the call. If I replace `is_expression()` with `is_call()` this query works and none of the test fails, so maybe you just misunderstood what the (confusingly named) `is_expression()` does?

**Comment by mgirlich** [comment]
I already had a PR prepared for this (though not on Github) and considered using `is_symbolic()` instead of the incorrect `is_symbol() | is_expression()`. But maybe `is_symbol() | is_call()` is easier to understand.
