### ISSUE TITLE
FR: Nudge users via thin wrapper methods for tbl_lazy methods of names(), $

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dbplyr#1056]
Successor to #997, #1010.

That issue/PR was about defining a `names.tbl_lazy()` method that behaves more like what new users might expect out of running `names()` on a lazy table, namely that it returns the column names.

But as discussed (https://github.com/tidyverse/dbplyr/pull/1010#issuecomment-1322274125), this is a bit fraught because other basic R functions like `str()` induce some implicit requirements on consistency among `names()` and related operators like `$`, `[`, and `[[`, so we decided against creating such a method and instead forcing users to call `colnames()`.

Nevertheless, I think it's still helpful to nudge users in the right direction if they're using `names()` on a `tbl_lazy` object, since the value will be confusing and very few users will actually want the results.

The same can be said for `$` -- even if it doesn't return a column, I would guess that's what the vast majority of people who wind up using `$` on a `tbl_lazy` object will have intended.

We can improve the UX here by turning these methods into simple wrappers that nudge the user the first time they use `names()`, but then fall silent to get out of their hair, e.g. (rough sketch)

```r
names.tbl_lazy = function(x) {
  if (!cache$warned) { cache$warned <- TRUE; message("Did you mean colnames()?") }
  NextMethod("names")
}
```

**Comment by fh-mthomson** [comment]
I'm using the development version on `main` (at 861b08fc4b538822299fb8cb414a98a6b066ad0d) and `names(lazy_tbl)` now _does_ return column names. Given the discussion above, is this change intentional?

Context: we'd been using `"lazy_query" %in% names(lazy_tbl)` to gate downstream behaviour. We can always adapt to instead use something more explicit (e.g., `!is.null(lazy_tbl[["lazy_query"]])`); however, as described, it is tricky to have named elements not actually captured via the result of `names()`.

See definition [here](https://github.com/tidyverse/dbplyr/blob/main/R/tbl-lazy.R#L107-L110), added by @mgirlich in #1014 :
```
names.tbl_lazy <- function(x) {
  colnames(x)
}
```

Reprex:
``` r
library(dplyr, warn.conflicts = F)

con <- DBI::dbConnect(RPostgres::Postgres())

DBI::dbWriteTable(con, "dataframe", tibble(x = 1))

lazy_tbl <- tbl(con, "dataframe")

names(lazy_tbl)
#> [1] "x"

"lazy_query" %in% names(lazy_tbl)
#> [1] FALSE
lazy_tbl[["lazy_query"]]
#> From: dataframe
#> <Table: dataframe>
lazy_tbl$lazy_query
#> From: dataframe
#> <Table: dataframe>
```

<sup>Created on 2023-01-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mgirlich** [comment]
This was done before this discussion and should be reverted...

**Comment by mgirlich** [comment]
@MichaelChirico I removed the need for the `names()` method in my PR. Unfortunately, it is quite annoying to simply call inform user when the `names()` method is called as a simple assignment in RStudio leads to the `names()` method being called.
