### ISSUE TITLE
export `last_value_sql()`

### ISSUE THREAD

**Issue by copernican** [tidyverse/dbplyr#1079]
As described in #1026, `fill()` doesn't work for Presto/Trino. I am opening a PR for RPresto as requested in #1065. Would it be possible to export the generic for `last_value_sql()` so that I can avoid `:::` or similar when referring to the function?

**Comment by mgirlich** [comment]
`fill()` now uses the newly gained `na_rm` argument of `last()` so that `last_value_sql()` isn't needed anymore.
You can look at https://github.com/tidyverse/dbplyr/blob/main/R/backend-.R#L386 and https://github.com/tidyverse/dbplyr/blob/main/R/translate-sql-window.R#L255 for the implementation in dbplyr.
