### ISSUE TITLE
Add support for `WITH RECURSIVE`

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dbplyr#1108]
As suggested in #1107 it would be nice to have a verb for recursive CTEs. For local data frames one could solve the issue with a for loop but this isn't an option for database tables.
@hadley have you ever considered adding this to dplyr or dbplyr? What do you think of adding this feature?

**Comment by hadley** [comment]
e.g. for handling hierarchical relationships where each row has an `id` and `parent_id` and you want to get all children? It hasn't come up in dplyr.

**Comment by hadley** [comment]
Closing since we don't currently have concrete use case.

**Comment by cthombor** [comment]
Hi, I think I have a use case for #1108.  

Then again, it wouldn't surprise me if someone wizardly knows how to implement a recursive filter efficiently in the tidyverse.

Below is a reprex to illustrate the kernel of modelling code I'm currently developing -- which annoyingly lurches briefly out of the tidyverse, so that I can use `stats::filter()`. 

(The reprex is simplified hugely from my actual use-case: of analysing time-series logs from my e-NV200 e-motorhome.  I'm now alpha-testing a simple model of how the temperature of its traction battery varies with its instantaneous amperage.  The kernel of the simulation is the calculation of an exponentially-lagged "Joule heat" energy, with a time constant that is experimentally derived by an `nlm()` fit to the `lambda` parameter in the simulation.   I briefly considered using `tsibble`; but I'm wary of classes with multiple inheritances that are intended to maintain backwards compatibiity... and `tsibble` is currently in v1.2.0 so maybe has some rough edges or instabilities I'd rather not be dealing with.... given that all I want from `xts` is an interface to a simple recursive filter à la Poisson, and a convenient `plot()` routine for visualising the output of my simulation.)

``` r
library(tidyverse)
library(zoo)
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
library(xts)
#> 
#> ######################### Warning from 'xts' package ##########################
#> #                                                                             #
#> # The dplyr lag() function breaks how base R's lag() function is supposed to  #
#> # work, which breaks lag(my_xts). Calls to lag(my_xts) that you type or       #
#> # source() into this session won't work correctly.                            #
#> #                                                                             #
#> # Use stats::lag() to make sure you're not using dplyr::lag(), or you can add #
#> # conflictRules('dplyr', exclude = 'lag') to your .Rprofile to stop           #
#> # dplyr from breaking base R's lag() function.                                #
#> #                                                                             #
#> # Code in packages is not affected. It's protected by R's namespace mechanism #
#> # Set `options(xts.warn_dplyr_breaks_lag = FALSE)` to suppress this warning.  #
#> #                                                                             #
#> ###############################################################################
#> 
#> Attaching package: 'xts'
#> The following objects are masked from 'package:dplyr':
#> 
#>     first, last

tb <- tibble(sample_value = runif(100),
             sample_time = make_date() + seq(1:100))

tb[40, 1] <- NA
w <- which(is.na(tb$sample_value)) # location(s) of missing sample(s)
wend <- c(w, length(tb) + 1) # append a 0-length "ghost segment"

EMA_parameter <- 0.25

tbts <- as.xts(tb)
for (i in seq(length(w))) {
  # apply filter to all non-ghost segments
  tbts[wend[i]:(wend[i + 1] - 1)] <-
    stats::filter(tbts[wend[i]:(wend[i + 1] - 1)] * EMA_parameter,
                  1. - EMA_parameter,
                  method = "recursive",
                  init = 0.)
}
plot(tbts)


Created on 2026-02-24 with [reprex v2.1.1](https://reprex.tidyverse.org/)
```
