### ISSUE TITLE
Dates in MS SQL aren't escaped properly

### ISSUE THREAD

**Issue by thothal** [tidyverse/dbplyr#1213]
```r
library(dbplyr)
escape(as.POSIXlt("2022-12-31 12:59:15"), con = simulate_mssql())
## <SQL> '2022-12-31T12:59:15Z'
## should be: 
## <SQL> '2022-12-31T12:59:15'
```

`T-SQL` does not allow for the time zone letter to be added to the literal (cf. [the specifications for time literals](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver16#supported-string-literal-formats-for-datetime)).

Thus, we would need to specify an own `sql_escape_datetime` routine for `Microsoft SQl Server` where we remove the (forced) conversion to `UTC`:

```r
`sql_escape_datetime.Microsoft SQL Server` <- function (con, x)  {
    x <- strftime(x, "%Y-%m-%dT%H:%M:%S")
    sql_escape_string(con, x)
}
```

**Comment by erikvona** [comment]
The assumption that SQL server doesn't allow for time zone letters is incorrect. Modern SQL server has a `datetimeoffset` type which accepts `'2022-12-31T12:59:15Z'` as a valid literal, see [here](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-ver16#supported-string-literal-formats-for-datetimeoffset). 

An oddity is that dbplyr sets timezones to UTC instead of preserving them in literals, but this could be considered fine. E.g.:

``` r
library(dbplyr)
escape(as.POSIXct("2022-12-31 12:59:15", tz ="US/Central"), con = simulate_mssql())
#> <SQL> '2022-12-31T18:59:15Z'
```

I think that's good enough. One could argue this makes it harder to work with dates and dbplyr should be using `lubridate::format_ISO8601` or an implementation of that and preserve the timezone, but that'd be a breaking change.

There are also some oddities in how SQL server processes datetime literals with time offsets (if it guesses the literal is a `DATETIME` and it's not cast to a `DATETIMEOFFSET` the offset may be ignored) but that's not something for dbplyr to worry about. We could at most argue that dbplyr should provide literals including a `CAST` to the right type
