### ISSUE TITLE
Progress bar for collect()

### ISSUE THREAD

**Issue by Tazinho** [tidyverse/dbplyr#1449]
Not sure if possible but `collect()` would really benefit from a progress bar.

E.g. code like this

```r
tbl(con, "table_name") %>% collect(.progress = TRUE)
```
providing progress bar like this

![image](https://github.com/tidyverse/dbplyr/assets/11295192/0f3cbb2a-4458-485a-b672-bc4ac8c06a7c)

Great package by the way. Using it a lot ATM.

**Comment by hadley** [comment]
I agree that this would be very nice, but unfortunately I don't think there's any way to do it since DBI doesn't expose any information about the retrieval process. (And in general, I'm not sure if databases even know how many rows there might be to return before they actually execute the entire query).
