### ISSUE TITLE
Add support for quantile()

### ISSUE THREAD

**Issue by halldc** [tidyverse/dbplyr#169]
Would it be possible to add support for the [`quantile()`](https://www.rdocumentation.org/packages/stats/versions/3.5.1/topics/quantile) function?

Quite a few databases support `PERCENTILE_CONT` and `PERCENTILE_DISC`, which I think could make this possible (e.g. Google BigQuery, PostgreSQL, and Redshift).

I'd be willing to help of course, but would need some pointers on where to start.

**Comment by Prometheus77** [comment]
I feel like there might be a way to do this with `win_over()`. I'm assuming you want to be able to write an expression such as:

`SELECT P90 = PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY Score) OVER (PARTITION BY [Month])`

Here's the documentation for win_over:
https://dbplyr.tidyverse.org/reference/win_over.html

The closest I can get to this is:

`dbplyr::win_over(sql("percentile_cont(0.9)"), "Month", order = "score")`

Which yields:

`<SQL> percentile_cont(0.9) OVER (PARTITION BY "Month" ORDER BY "score")`

I'd have to spend more time with it to see if I can get it to do what I want.

**Comment by hadley** [comment]
@halldc If you wanted to help, the place to start would be by making a list of databases (starting with SQLite, MySQL, and Postgres, and then continuing as long as you like) with a link to the documentation for their quantile function.

**Comment by edavidaja** [comment]
I'll work on this

**Comment by edavidaja** [comment]
# percentile functions for databases

## msft sql server

### [syntax:](https://docs.microsoft.com/en-us/sql/t-sql/functions/ntile-transact-sql?view=sql-server-2017) 
```
NTILE (integer_expression) OVER ( [ <partition_by_clause> ] < order_by_clause > )  
```

## teradata

### [syntax:](https://www.wisdomjobs.com/e-university/teradata-tutorial-212/partitioning-data-using-the-quantile-function-6086.html)

```
SELECT QUANTILE (<partitions>, <column-name>  ,<sort-key> [DESC | ASC])
  FROM  <table-name>
  [QUALIFY  QUANTILE (<column-name>) {< | > | = | <= | >=}  <number-of-rows>]
  ;
```

## hive

Doesn't appear to be a built in quantile function here  
https://stackoverflow.com/a/32886820/5161539

### [syntax:](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF)

```{sql}
 select item,p,percentile_approx(value,array(0.25,0.50.0.75)) 
 from t1 where p=1 group by item,p;
```

```{sql}
select item,p,percentile_approx(value,0.5) 
from t1 where p=1 group by item,p;
```

## impala

### [syntax:](https://www.cloudera.com/documentation/enterprise/5-6-x/topics/impala_analytic_functions.html#ntile)

```
NTILE (expr [, offset ...]
  OVER ([partition_by_clause] order_by_clause)
```

## postgres

### [syntax:](https://www.postgresql.org/docs/9.4/functions-aggregate.html#FUNCTIONS-ORDEREDSET-TABLE)

```
percentile_cont(fraction) WITHIN GROUP (ORDER BY sort_expression)
```

## redshift

### [syntax:](https://docs.aws.amazon.com/redshift/latest/dg/r_WF_NTILE.html)

```
NTILE (expr)
OVER ( 
[ PARTITION BY expression_list ] 
[ ORDER BY order_list ]
)
```

## salesforce

### [syntax:](https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_saql.meta/bi_dev_guide_saql/bi_saql_fn_agg_pc.htm)

```
percentile_cont(p) within group (order by expr [asc | desc])
```

## monetdb

### [syntax:](https://www.monetdb.org/Documentation/SQLreference/StatisticFunctions)

```
QUANTILE  '(' scalar_expr ',' scalar_expr ')'
```

## mysql

as of 8.0

### [syntax:](https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html#function_ntile)

```
NTILE(N) over_clause
```

## mariaDb

### [syntax:](https://mariadb.com/kb/en/library/percentile_cont/)

```
SELECT name, PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY star_rating) 
  OVER (PARTITION BY name) AS pc 
  FROM book_rating;
```

## sqlite

SQLite doesn't really handle window functions, but here's an example median

### [syntax:]()

```{sql}
SELECT x
FROM MyTable
ORDER BY x
LIMIT 1
OFFSET (SELECT COUNT(*)
        FROM MyTable) / 2
```

Someone has put some [implementing C code for a percentile function here](https://github.com/mackyle/sqlite/blob/master/ext/misc/percentile.c) 

## bigquery

### [syntax:](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#ntile)

```
NTILE(constant_integer_expression)
```

## notes

postgres, mariadb, salesforce, and hive implement via some continuous percentile function

hive contains a percentile function but no quantile function per se, but the array return should be able to make it happen

It's not clear how one would make this work in SQLite since the window function support is pretty limited

**Comment by krlmlr** [comment]
One way to look at the SQL translation without having access to a real database:

``` r
library(tidyverse)
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

tbl_lazy(iris, src = simulate_dbi("PostgreSQLConnection")) %>%
  mutate(q = quantile(Petal.Length, .25)) %>%
  show_query()
#> <SQL> SELECT `Sepal.Length`, `Sepal.Width`, `Petal.Length`, `Petal.Width`, `Species`, QUANTILE(`Petal.Length`, 0.25) AS `q`
#> FROM `df`
```

<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
@edavidaja that just hides the details so I have to do even more clicking to see the details. I basically want a one screen cheatsheet that lets me see the variation at a glance.

**Comment by halldc** [comment]
Thanks for your work on this @edavidaja ! I'm hoping that in a few weeks' time I should be able to contribute to this task, if that helps.

By the way, I see in your table that you're mixing `NTILE` with `PERCENTILE`/`QUANTILE` functions, but these are used in different contexts. 
- The `NTILE` function divides the data into a specified number of ranked groupings, and associates each row with one of these groups. See [Redshift example](https://docs.aws.amazon.com/redshift/latest/dg/r_Examples_of_NTILE_WF.html). This is similar to [`dplyr::ntile()`](https://dplyr.tidyverse.org/reference/ranking.html).
- The `PERCENTILE`/`QUANTILE` functions yield an aggregate statistic (e.g. the median is the 50th percentile). See [Redshift example](https://docs.aws.amazon.com/redshift/latest/dg/r_Examples_of_PERCENTILE_CONT_WF.html). This is similar to the R function [`quantile()`](https://www.rdocumentation.org/packages/stats/versions/3.5.1/topics/quantile).

**Comment by hadley** [comment]
@edavidaja that is perfect, thank you!

**Comment by hadley** [comment]
A few more tweaks to make it a bit easier for me to parse:

* [sql-server]: `PERCENTILE_CONT(p) WITHIN GROUP (...)`
* [teradata]: `APPROX_PERCENTILE(x, percentage)`
* [hive]: `PERCENTILE_CONT(x, array(p1, p2, ...))`
* [impala]: 
* [postgres]: `PERCENTILE_CONT(p) WITHIN GROUP (...)`
* [redshift]: `PERCENTILE_CONT(p) WITHIN GROUP (...)`
* [salesforce]: `PERCENTILE_CONT(p) WITHIN GROUP (...)`
* [monetdb]: `QUANTILE(x, p)`
* [mysql]: not supported
* [mariadb]: `PERCENTILE_CONT(p) WITHIN GROUP (...)`
* [sqlite]: not supported
* [bigquery]: `PERCENTILE_CONT(x, p)`

[sql-server]: https://docs.microsoft.com/en-us/sql/t-sql/functions/percentile-cont-transact-sql?view=sql-server-2017
[teradata]: https://teradata.github.io/presto/docs/0.167-t/functions/aggregate.html
[hive]: https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF
[impala]: https://issues.apache.org/jira/browse/IMPALA-4025
[postgres]: https://www.postgresql.org/docs/9.4/functions-aggregate.html#FUNCTIONS-ORDEREDSET-TABLE
[redshift]: https://docs.aws.amazon.com/redshift/latest/dg/r_Examples_of_PERCENTILE_CONT_WF.html
[salesforce]: https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_saql.meta/bi_dev_guide_saql/bi_saql_fn_agg_pc.htm
[monetdb]: https://www.monetdb.org/Documentation/SQLreference/StatisticFunctions
[mysql]: https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html
[mariadb]: https://mariadb.com/kb/en/library/percentile_cont/
[sqlite]: https://www.sqlite.org/windowfunctions.html
[bigquery]: https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#percentile_cont

**Comment by hadley** [comment]
For the databases that support the `PERCENTILE_CONT()` window function, I don't see how we can use this in aggregation (i.e. `summarise()`) context.

**Comment by hadley** [comment]
Oops, those aren't window functions, but are "ordered-set aggregate" functions, and they work just fine with `GROUP BY`:

``` r
library(DBI)

con <- dbConnect(RPostgres::Postgres())
dbGetQuery(con, "
  SELECT cyl, PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY mpg) 
  FROM mtcars 
  GROUP BY cyl  
")
#>   cyl percentile_cont
#> 1   4            26.0
#> 2   6            19.7
#> 3   8            15.2
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by halldc** [comment]
Thanks @hadley! 🎉

**Comment by hadley** [comment]
Looks like the link to teradata was actually to teradata's distribution of presto. It seems like teradata actually is ansi compliant: https://docs.teradata.com/reader/756LNiPSFdY~4JcCCcR5Cw/RgAqeSpr93jpuGAvDTud3w
