### ISSUE TITLE
Add group_map() and group_walk() methods

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#203]
Presumably re-using code from `do()`

**Comment by hadley** [comment]
Will wait for next release since dplyr interface is still changing.

**Comment by hadley** [comment]
Since these are going away, I think we can close this now.

**Comment by bschneidr** [comment]
This would still be valuable. It would be helpful to be able to map a function across groups of data, only pulling into memory one group's data at a time. For example, when working with American Community Survey data, we might want to fit a regression separately for each state's data, and due to memory constraints we only want to pull one state's data into memory at a time. So it'd be helpful to be able to do something like

```{r}
big_dataset_tbl |>
  group_by(STATE) |>
  group_map(
    ~ .x |> 
        collect() |> 
        glm(data = _, formula = y ~ x) |> 
        broom::tidy()
  )
```
