### ISSUE TITLE
Postgres SQL translation of UNION adds extra parentheses

### ISSUE THREAD

**Issue by admoseremic** [tidyverse/dbplyr#326]
When using the union function, it translates the SQL to include parentheses around the tables surrounding the union. For example,

`my_var = data_frame1 %>% union(data_frame2)`

results in SQL of:

`(SELECT "v1", "v2", "v3" FROM "data_frame1") UNION (SELECT "v1", "v2", "v3" FROM "data_frame2")`

which seems to cause issues with some Postgres evaluations - what I'm needing is for it to evaluate to the same thing but without the parentheses:

`SELECT "v1", "v2", "v3" FROM "data_frame1" UNION SELECT "v1", "v2", "v3" FROM "data_frame2"`

**Comment by hadley** [comment]
Can you please provide a minimal reproducible example using the [reprex](http://reprex.tidyverse.org) package? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never made a minimal reprex before, there is lots of good advice [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
