### ISSUE TITLE
Adding custom comments to the generated SQL

### ISSUE THREAD

**Issue by CerebralMastication** [tidyverse/dbplyr#350]
I have a weird use case where I’d like to add a custom comment to the top of autogenerated SQL from dbplyr. We’re having some database contention issues and my database admins would like some header comments & info so they can see what’s running and why. I’m not familiar with the dbplyr code base but happy to hack around a bit. I can imagine something like an `sql_comment(“somecomment”)` operator that would add a comment and a CR to the generated SQL. Where would something like this live in the code base? Is there an easier way using a custom operator that will just inject my comment in? 

Cheers, 

JD

**Comment by ianmcook** [comment]
I gave this a try yesterday, but it didn't work out as I had hoped because of how dbplyr builds up a nested data structure and then recurses into it to create the SQL. This makes it impractical to create a commenting mechanism in the way we described above, because this requires a separate, expensive recursion into the `tbl_sql` object at the time when it's `print()`ed or `collect()ed` or `compute()`d, just to assemble the comment.

However, I think what _would_ work is to simply add an optional `comment` argument to the `print()`, `collect()`, `compute()`, and `as.data.frame()` methods for `tbl_sql` objects. @CerebralMastication would the users you're working with be willing and able to _explicitly_ call one of these methods when needed, instead of using implicit methods of calling them?

**Comment by CerebralMastication** [comment]
oh yeah I think so @ianmcook. We typically call `collect` explicitly the workflow, so adding the comment argument in `collect` would totally scratch my itch.

**Comment by hadley** [comment]
I'm going to assume you've figured out something in the last year 😄 Unfortunately I think it will be relatively challenging to add arbitrary comments and since it's a rather limited use case, it's unlikely to ever climb to the top of my todo list.

**Comment by peishenwu** [comment]
I have an use case for this.
Our company uses dplyr/dbplyr/bigrquery as our data lake pipeline, orchestrated with Airflow.
It's very difficult to attribute growing query costs to each individual job script, because the authentication process we use has only a single common service token. 
But it would be handy if we can insert, say, the job script's filename as comment into the generated SQL query. 

I have tried an possible solution, it works for me, maybe it would work for you.

``` 
bq_add_comment <- function(qry, comment){
  commented_query <- paste0("#",comment,"\n",as.character(dbplyr::sql_render(qry)))
  
  vars <- DBI::dbFetch(DBI::dbSendQuery(qry$src$con, paste0("select * from (",commented_query,") limit 0")), 0)
  vars <- names(vars)
  
  subclass <- class(qry$src$con)[[1]]
  make_tbl(purrr::compact(c(subclass, "sql", "lazy")), 
           ops = dbplyr:::op_base_remote(sql(commented_query), vars),
           src = qry$src)
}# end function
``` 

use it as follows
``` 
tbl(con, "my_dataset.my_table") %>% show_query() # compare
tbl(con, "my_dataset.my_table") %>% bq_add_comment("my_comment") %>% show_query() # compare
```
