### ISSUE TITLE
pull raises error with zero rows

### ISSUE THREAD

**Issue by dkulp2** [tidyverse/dbplyr#352]
I think pull should return an empty typed vector or NULL if there are no results. This seems to be inconsistent. 

If I create a table in postgres and pull a column from a remote table with zero rows, then I get a subscript out of bounds error. If I use memdb_frame, then it works as expected.

A workaround is using collect and '[[', but the motivation behind pull() is a convenience to avoid this.

```r
> dbWriteTable(con, 'foo', tibble(x=1:10))
[1] TRUE
> filter(tbl(con,'foo'), x<1)
# Source:   lazy query [?? x 2]
# Database: postgres 11.2.0 [...]
> filter(tbl(con,'foo'), x<1) %>% pull(x)
Error in .subset2(x, i) : subscript out of bounds
> df <- dbplyr::memdb_frame(x=1:10)
> filter(df, x<1) %>% pull(x)
integer(0)
```

**Comment by hadley** [comment]
Can you please provide a minimal reproducible example using the [reprex](http://reprex.tidyverse.org) package? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never made a minimal reprex before, there is lots of good advice [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by dkulp2** [comment]
You can only reproduce this error if you have an available postgres database, but here is a slightly more detailed example using reprex. It shows that the behavior using RSQlite, memdb_frame, and tibbles is different from RPostgreSQL.

``` r
test_pull <- function(df) {
  assertthat::assert_that(length(filter(df, x<1) %>% pull(x))==0)  
}

library(DBI)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, 'foo', tibble(x=1:10))
df <- tbl(con,'foo')
test_pull(df)
#> [1] TRUE

df <- dbplyr::memdb_frame(x=1:10)
test_pull(df)
#> [1] TRUE

df <- tibble(x=1:10)
test_pull(df)
#> [1] TRUE

con <- dbConnect(RPostgreSQL::PostgreSQL())
dbWriteTable(con, 'foo', tibble(x=1:10), temporary=TRUE)
#> [1] TRUE
df <- tbl(con,'foo')
test_pull(df)  # fails
#> Error in .subset2(x, i): subscript out of bounds
```

<sup>Created on 2019-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This looks like the root cause:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

con <- DBI::dbConnect(RPostgreSQL::PostgreSQL(), dbname = "test", host = "localhost")
DBI::dbWriteTable(con, 'foo', tibble(x=1:10), temporary=TRUE)
#> Warning in postgresqlWriteTable(conn, name, value, ...): table foo exists in
#> database: aborting assignTable
#> [1] FALSE
df <- tbl(con,'foo')

df_empty <- df %>% filter(x < 1)
collect(df_empty)
#> # A tibble: 0 x 0
```

<sup>Created on 2019-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So this is actually a bug in the RPostgresSQL package. Unfortunately, that package is basically unmaintained, but you should be able to switch to RPostgres, which is, and where this bug has already been fixed:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

con <- DBI::dbConnect(RPostgreSQL::PostgreSQL(), dbname = "test", host = "localhost")
DBI::dbWriteTable(con, 'foo', tibble(x=1:10), temporary=TRUE)
#> Warning in postgresqlWriteTable(conn, name, value, ...): table foo exists in
#> database: aborting assignTable
#> [1] FALSE
DBI::dbGetQuery(con, "SELECT * FROM foo WHERE x < 1")
#> data frame with 0 columns and 0 rows

con2 <- DBI::dbConnect(RPostgres::Postgres(), dbname = "test", host = "localhost")
DBI::dbGetQuery(con2, "SELECT * FROM foo WHERE x < 1")
#> [1] row.names x        
#> <0 rows> (or 0-length row.names)

con2 %>% 
  tbl("foo") %>% 
  filter(x < 1) %>% 
  pull()
#> integer(0)
```

<sup>Created on 2019-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
