### ISSUE TITLE
SQL translation taking out parentheses when translating from R expressions

### ISSUE THREAD

**Issue by wangyuchen** [tidyverse/dbplyr#393]
``` r
library(rlang)
library(dbplyr)

a <- expr(1 + 1)

# correctly add parentheses in R
expr(!!a / 2)
#> (1 + 1)/2


# but not in SQL
dbplyr::translate_sql(b = !!a / 2)
#> <SQL> 1.0 + 1.0 / 2.0 AS b
```

<sup>Created on 2019-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

When I debug into `translate_sql`, the R expression is first unquoted correctly to `(1 + 1) / 2`, but then passed to `eval_tidy` where the parentheses are somehow taken out.

**Comment by hadley** [comment]
That's because the parentheses are added by R's deparser, they don't actually exist in the AST:

``` r
library(rlang)

a <- expr(1 + 1)
b <- expr(!!a / 2)
lobstr::ast(!!b)
#> █─`/` 
#> ├─█─`+` 
#> │ ├─1 
#> │ └─1 
#> └─2

lobstr::ast((1 + 1) / 2)
#> █─`/` 
#> ├─█─`(` 
#> │ └─█─`+` 
#> │   ├─1 
#> │   └─1 
#> └─2
```

<sup>Created on 2020-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(There's bit more info at https://adv-r.hadley.nz/quasiquotation.html#non-standard-ast)

I'm not sure if there's much I can do about this in dbplyr, but it seems like it should be a fairly esoteric problem because it only arises when manually creating expressions.
