### ISSUE TITLE
Diagramming how / when subqueries are created

### ISSUE THREAD

**Issue by machow** [tidyverse/dbplyr#492]
Hey! I've been working for the last couple years on dplyr-like SQL support in python, as part of [siuba](https://github.com/machow/siuba).

One thing I've noticed is that dbplyr has really streamlined when it creates subqueries. I've been trying to represent a mental model behind when a subquery should be created, and **would be really curious to know if there are similar tools / representations people use when developing dbplyr :).**

The idea is that you can represent the order that SQL "handles" a query using the acronym FWG SOL (I say "frog soul"):
From, Where, Group by, Select, Order by, Limit.

A sequence of verbs can be represented using the x-axis, and the acronym down the y-axis. Whenever a sequence doesn't move downward, it has to create a subquery:

![image](https://user-images.githubusercontent.com/2574498/91588985-ff54d480-e926-11ea-9c11-cd1b930e1902.png)

So in this example, the blue sequence has to create a subquery, while the orange doesn't.

```R
# blue sequence: head -> summarize
mtcars %>% head() %>% group_by(cyl) %>% summarize(avg = mean(hp))

# orange sequence (no subquery needed): summarize -> head
mtcars %>% group_by(cyl) %>% summarize(avg = mean(hp)) %>% head()
```

This idea sort of breaks down for mutate, since there a subquery only needs to be created if it references a previous column. Each query can be thought to hold a batch of columns (including the previous ones it had access to). The example below shows how two mutates could produce two subqueries.

![image](https://user-images.githubusercontent.com/2574498/91592037-e69aed80-e92b-11ea-89b1-0faa285bc89f.png)

The purple subquery would be to reference columns in the original table, and the green subquery to refer to a column created within the same mutate.

Similarly, a filter might need to create subqueries for its "where" and "select" portions, depending on the intermediate calculations.

Are there similar ways for thinking about subqueries when developing dbplyr? I still need to look closer at some of the recent improvements dbplyr added, but thought I'd check before jumping in!

**Comment by hadley** [comment]
I don't think there's much big picture thinking, apart from understanding the order of SQL queries that you point out above. Most of the recent advancements have been carefully thinking through when you can skip a subquery, e.g. https://github.com/tidyverse/dbplyr/blob/master/R/verb-select.R#L29-L55. I think dbplyr originally started out as making a subquery for basically every dplyr verb, and then over time I've figured out various ways to reduce that.

Modelling the SQL query at multiple levels of abstraction (e.g. dplyr verbs, "operations", query objects, and SQL strings) seems to be a useful design because some optimisations are only obvious at specific levels of abstraction.
