### ISSUE TITLE
C stack usage is too close to the limit

### ISSUE THREAD

**Issue by p-schaefer** [tidyverse/dbplyr#719]
I'm having an issue that might be related to #482. I'm developing a shiny app to interface with a a mySQL database with 120 tables. For some queries I have to join upwards of 20 tables from which I then filter the data. But at some point, as I stack filters on, I get an error about C Stack Usage too close to the limit, and I believe it has to do with the length of the sql query.  

I'm using dbplyr's ```left_joins()``` and  ```filter()``` in for loops to accomplish this, is there perhaps a better way?

Sorry I don't know the best way of generating an example.

**Comment by tomjemmett** [comment]
I've just had a very similar error occur, I'm query against a Microsoft Sql Server database on Windows, but here are steps I can use to reproduce the error (at least, pseudo steps, actual database/column names are redacted):

``` r
# this fails
my_tb <- tbl(con, "table") |> filter(stuff == "thing")
# but this succeeds, using %>% instead of |>
my_tb <- tbl(con, "table") %>% filter(stuff == "thing")
# strangely, this works
tbl(con, "table") |> filter(stuff == "thing")
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by mgirlich** [comment]
I created a reprex

```r
library(dbplyr)
library(dplyr)
lf <- lazy_frame(x = 1)

gen_nested_lf <- function(n) {
  out <- lf
  for (i in 1:n) {
    out <- left_join(out, lf, by = "x") %>% 
      filter(x == 1)
  }
  
  out
}

query <- remote_query(gen_nested_lf(72))
```

With CRAN dbplyr the maximum that works for me is `n = 72`. The dev version (probably due to the new render pipeline) gives a slightly different error and works until `n = 141`. I think this is reasonable and I might come back to this later.
Another issue is that at some point the query parser of the database produces errors because the query gets too long. So, to fix this properly is quite a bit of work I'm afraid.

As a workaround you can use `compute()`, e.g. something like

```r
out <- lf
for (i in 1:n) {
  out <- left_join(out, lf, by = "x") %>% 
    filter(x == 1)
  
  if (i %% 10 == 0) {
    out <- compute(out, cte = TRUE)
  }
}
```

**Comment by fabkury** [comment]
I had the same problem when building a lazy table incrementally. Using collapse() solved it for me. I didn't want the results to get computed and stored in a temporary table, as compute() does.
