### ISSUE TITLE
dbplyr cannot be loaded

### ISSUE THREAD

**Issue by sitendug** [tidyverse/dbplyr#832]
Whenever I try to load the package tidyverse  I get an error that is linked to dbplyr. I am running r version 4.1.3

> library(dbplyr)
Error in completeSubclasses(classDef2, class1, obj, where) : 
  trying to get slot "subclasses" from an object of a basic class ("NULL") with no slots
Error: package or namespace load failed for ‘dbplyr’:
 .onLoad failed in loadNamespace() for 'dbplyr', details:
  call: setClass(cl, contains = c(prevClass, "VIRTUAL"), where = where)
  error: error in contained classes ("character") for class “ident”; class definition removed from ‘dbplyr’
> 
Error: attempt to use zero-length variable name

**Comment by jmfrater** [comment]
I am having the same problem. I am also running R version 4.1.3

**Comment by mgirlich** [comment]
This was posted before https://github.com/tidyverse/dbplyr/issues/779 and it turned out not to be a dbplyr issue but an issue with other packages (e.g. Brobdingnag) resp. R itself. You can either update to the dev version of the packages mentioned in the other thread. Or you to wait for the next R version where this is fixed.
