### ISSUE TITLE
Allow `rows_insert()` to work with data frame `y`

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#891]
That would be a bit more direct than having to use `copy_to()` or `copy_inline()` and would generate simpler SQL.

**Comment by hadley** [comment]
i.e. generate


```sql
INSERT INTO table(col1, col2)
VALUES ((1, 2), (3, 4))
```

vs what you'd get from using `copy_inline()`:

```sql
INSERT INTO table
SELECT CAST(`col1` AS REAL) AS `col1`, CAST(`col2` AS REAL) AS `col2`
FROM (
  SELECT NULL AS `col1`, NULL AS `col2`
  WHERE (0 = 1)
  UNION ALL
  VALUES (1, 2), (3, 4)
) AS `values_table`
```

**Comment by mgirlich** [comment]
Your idea doesn't quite work 😢 

We definitely need the column names for `rows_insert()` due to `by`

```sql
INSERT INTO ...
SELECT *
FROM ... AS `...y`
WHERE NOT EXISTS (
  SELECT 1 FROM `df`
  -- here we need the column names
  WHERE (`df`.`x` = `...y`.`x`)
)
```

The very simple version would only work for `rows_append()`.
For `rows_insert()` one could probably get rid of the casts. Maybe this would also work for `rows_update()`.

So, I'm not sure it would really be worth the effort.

**Comment by hadley** [comment]
Ah that sucks. So definitely not worth the effort.
