### ISSUE TITLE
`count()` returns group with >=2 groups in `...`

### ISSUE THREAD

**Issue by jmbarbone** [tidyverse/dbplyr#940]
Only the last group is dropped after `count()` is finished.  Similar to issue from https://github.com/tidyverse/dtplyr/issues/356.

Check against current github versions.

``` r
library(dplyr, warn.conflicts = FALSE)
packageVersion("dplyr")
#> [1] '1.0.99.9000'
packageVersion("dbplyr")
#> [1] '2.2.1.9000'

con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(con, mtcars)

con %>% 
  tbl("mtcars") %>% 
  count(cyl, vs) %>% 
  # should return n 5; but is still grouped
  count()
#> # Source:   SQL [3 x 2]
#> # Database: sqlite 3.38.5 [:memory:]
#>     cyl     n
#>   <dbl> <int>
#> 1     4     2
#> 2     6     2
#> 3     8     1

# returns as grouped_df
con %>% 
  tbl("mtcars") %>% 
  count(cyl, vs, am) %>% 
  collect()
#> # A tibble: 7 × 4
#> # Groups:   cyl, vs [5]
#>     cyl    vs    am     n
#>   <dbl> <dbl> <dbl> <int>
#> 1     4     0     1     1
#> 2     4     1     0     3
#> 3     4     1     1     7
#> 4     6     0     1     3
#> 5     6     1     0     4
#> 6     8     0     0    12
#> 7     8     0     1     2
```

<sup>Created on 2022-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mgirlich** [comment]
The issue is that there are two count methods:

* in dplyr there is `count.tbl_sql()`
* in dbplyr there is `count.tbl_lazy()`

Now `tbl(con, "mtcars")` has the classes

* `tbl_SQLiteConnection`
* `tbl_dbi`
* `tbl_sql`
* `tbl_lazy`
* `tbl`

Therefore, the dplyr method wins. I created a dplyr issue to remove this method https://github.com/tidyverse/dplyr/issues/6338.
